// Code generated by protoc-gen-go. DO NOT EDIT.
// source: event.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type BaseEvent struct {
	EventId       string `protobuf:"bytes,1,opt,name=event_id,json=eventId" json:"event_id,omitempty"`
	EventType     string `protobuf:"bytes,2,opt,name=event_type,json=eventType" json:"event_type,omitempty"`
	AggregateId   string `protobuf:"bytes,3,opt,name=aggregate_id,json=aggregateId" json:"aggregate_id,omitempty"`
	AggregateType string `protobuf:"bytes,4,opt,name=aggregate_type,json=aggregateType" json:"aggregate_type,omitempty"`
	RawData       []byte `protobuf:"bytes,5,opt,name=raw_data,json=rawData,proto3" json:"raw_data,omitempty"`
	Version       uint64 `protobuf:"varint,6,opt,name=version" json:"version,omitempty"`
	Timestamp     uint64 `protobuf:"varint,7,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *BaseEvent) Reset()                    { *m = BaseEvent{} }
func (m *BaseEvent) String() string            { return proto.CompactTextString(m) }
func (*BaseEvent) ProtoMessage()               {}
func (*BaseEvent) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{0} }

func (m *BaseEvent) GetEventId() string {
	if m != nil {
		return m.EventId
	}
	return ""
}

func (m *BaseEvent) GetEventType() string {
	if m != nil {
		return m.EventType
	}
	return ""
}

func (m *BaseEvent) GetAggregateId() string {
	if m != nil {
		return m.AggregateId
	}
	return ""
}

func (m *BaseEvent) GetAggregateType() string {
	if m != nil {
		return m.AggregateType
	}
	return ""
}

func (m *BaseEvent) GetRawData() []byte {
	if m != nil {
		return m.RawData
	}
	return nil
}

func (m *BaseEvent) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *BaseEvent) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type SaveEventsRequest struct {
	Events  []*BaseEvent `protobuf:"bytes,1,rep,name=events" json:"events,omitempty"`
	Version uint64       `protobuf:"varint,2,opt,name=version" json:"version,omitempty"`
}

func (m *SaveEventsRequest) Reset()                    { *m = SaveEventsRequest{} }
func (m *SaveEventsRequest) String() string            { return proto.CompactTextString(m) }
func (*SaveEventsRequest) ProtoMessage()               {}
func (*SaveEventsRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{1} }

func (m *SaveEventsRequest) GetEvents() []*BaseEvent {
	if m != nil {
		return m.Events
	}
	return nil
}

func (m *SaveEventsRequest) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

type SaveEventsResponse struct {
	Status *Status `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
}

func (m *SaveEventsResponse) Reset()                    { *m = SaveEventsResponse{} }
func (m *SaveEventsResponse) String() string            { return proto.CompactTextString(m) }
func (*SaveEventsResponse) ProtoMessage()               {}
func (*SaveEventsResponse) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{2} }

func (m *SaveEventsResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type LoadEventsRequest struct {
	AggregateId string `protobuf:"bytes,1,opt,name=aggregate_id,json=aggregateId" json:"aggregate_id,omitempty"`
}

func (m *LoadEventsRequest) Reset()                    { *m = LoadEventsRequest{} }
func (m *LoadEventsRequest) String() string            { return proto.CompactTextString(m) }
func (*LoadEventsRequest) ProtoMessage()               {}
func (*LoadEventsRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{3} }

func (m *LoadEventsRequest) GetAggregateId() string {
	if m != nil {
		return m.AggregateId
	}
	return ""
}

type LoadEventsResponse struct {
	Events []*BaseEvent `protobuf:"bytes,1,rep,name=events" json:"events,omitempty"`
	Status *Status      `protobuf:"bytes,2,opt,name=status" json:"status,omitempty"`
}

func (m *LoadEventsResponse) Reset()                    { *m = LoadEventsResponse{} }
func (m *LoadEventsResponse) String() string            { return proto.CompactTextString(m) }
func (*LoadEventsResponse) ProtoMessage()               {}
func (*LoadEventsResponse) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{4} }

func (m *LoadEventsResponse) GetEvents() []*BaseEvent {
	if m != nil {
		return m.Events
	}
	return nil
}

func (m *LoadEventsResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func init() {
	proto.RegisterType((*BaseEvent)(nil), "pb.BaseEvent")
	proto.RegisterType((*SaveEventsRequest)(nil), "pb.SaveEventsRequest")
	proto.RegisterType((*SaveEventsResponse)(nil), "pb.SaveEventsResponse")
	proto.RegisterType((*LoadEventsRequest)(nil), "pb.LoadEventsRequest")
	proto.RegisterType((*LoadEventsResponse)(nil), "pb.LoadEventsResponse")
}

func init() { proto.RegisterFile("event.proto", fileDescriptor4) }

var fileDescriptor4 = []byte{
	// 308 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xc1, 0x6a, 0xc2, 0x40,
	0x10, 0x65, 0xa3, 0x4d, 0xcc, 0x44, 0x0b, 0xee, 0x69, 0x2d, 0x2d, 0xa4, 0x01, 0x21, 0x27, 0x0f,
	0x16, 0x4a, 0xcf, 0xa5, 0x3d, 0x08, 0x3d, 0xad, 0xde, 0x65, 0x6c, 0x06, 0xf1, 0x90, 0xec, 0x36,
	0xbb, 0x2a, 0xfe, 0x6e, 0xbf, 0xa4, 0x38, 0x5a, 0x8d, 0x2d, 0x85, 0x1e, 0xf7, 0xbd, 0x37, 0x6f,
	0xde, 0x3c, 0x16, 0x12, 0xda, 0x50, 0xe5, 0x47, 0xb6, 0x36, 0xde, 0xc8, 0xc0, 0x2e, 0x6e, 0xba,
	0xef, 0xa6, 0x2c, 0x4d, 0x75, 0x40, 0xb2, 0x4f, 0x01, 0xf1, 0x33, 0x3a, 0x7a, 0xdd, 0xab, 0xe4,
	0x00, 0x3a, 0x2c, 0x9f, 0xaf, 0x0a, 0x25, 0x52, 0x91, 0xc7, 0x3a, 0xe2, 0xf7, 0xa4, 0x90, 0x77,
	0x00, 0x07, 0xca, 0xef, 0x2c, 0xa9, 0x80, 0xc9, 0x98, 0x91, 0xd9, 0xce, 0x92, 0xbc, 0x87, 0x2e,
	0x2e, 0x97, 0x35, 0x2d, 0xd1, 0xd3, 0x7e, 0xba, 0xc5, 0x82, 0xe4, 0x84, 0x4d, 0x0a, 0x39, 0x84,
	0xeb, 0xb3, 0x84, 0x5d, 0xda, 0x2c, 0xea, 0x9d, 0x50, 0x76, 0x1a, 0x40, 0xa7, 0xc6, 0xed, 0xbc,
	0x40, 0x8f, 0xea, 0x2a, 0x15, 0x79, 0x57, 0x47, 0x35, 0x6e, 0x5f, 0xd0, 0xa3, 0x54, 0x10, 0x6d,
	0xa8, 0x76, 0x2b, 0x53, 0xa9, 0x30, 0x15, 0x79, 0x5b, 0x7f, 0x3f, 0xe5, 0x2d, 0xc4, 0x7e, 0x55,
	0x92, 0xf3, 0x58, 0x5a, 0x15, 0x31, 0x77, 0x06, 0xb2, 0x19, 0xf4, 0xa7, 0xb8, 0x39, 0xdc, 0xe8,
	0x34, 0x7d, 0xac, 0xc9, 0x79, 0x39, 0x84, 0x90, 0xe3, 0x3b, 0x25, 0xd2, 0x56, 0x9e, 0x8c, 0x7b,
	0x23, 0xbb, 0x18, 0x9d, 0xaa, 0xd0, 0x47, 0xb2, 0xb9, 0x33, 0xb8, 0xd8, 0x99, 0x3d, 0x81, 0x6c,
	0xba, 0x3a, 0x6b, 0x2a, 0x47, 0x32, 0x83, 0xd0, 0x79, 0xf4, 0x6b, 0xc7, 0x05, 0x26, 0x63, 0xd8,
	0xdb, 0x4e, 0x19, 0xd1, 0x47, 0x26, 0x7b, 0x84, 0xfe, 0x9b, 0xc1, 0xe2, 0x32, 0xcf, 0xcf, 0x06,
	0xc5, 0xaf, 0x06, 0xb3, 0x39, 0xc8, 0xe6, 0xdc, 0x71, 0xe3, 0x3f, 0x0f, 0x39, 0x07, 0x0b, 0xfe,
	0x0a, 0xb6, 0x08, 0xf9, 0x53, 0x3c, 0x7c, 0x05, 0x00, 0x00, 0xff, 0xff, 0x9a, 0x45, 0x27, 0xe5,
	0x35, 0x02, 0x00, 0x00,
}
