// Code generated by protoc-gen-go. DO NOT EDIT.
// source: eventstore.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	eventstore.proto
	payment.proto

It has these top-level messages:
	Event
	EventFilter
	EventResponse
	Response
	PaymentCreatedCommand
	PaymentFinishedCommand
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Event struct {
	EventId       string `protobuf:"bytes,1,opt,name=event_id,json=eventId" json:"event_id,omitempty"`
	EventType     string `protobuf:"bytes,2,opt,name=event_type,json=eventType" json:"event_type,omitempty"`
	EventData     string `protobuf:"bytes,3,opt,name=event_data,json=eventData" json:"event_data,omitempty"`
	AggregateId   string `protobuf:"bytes,4,opt,name=aggregate_id,json=aggregateId" json:"aggregate_id,omitempty"`
	AggregateType string `protobuf:"bytes,5,opt,name=aggregate_type,json=aggregateType" json:"aggregate_type,omitempty"`
	Channel       string `protobuf:"bytes,6,opt,name=channel" json:"channel,omitempty"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Event) GetEventId() string {
	if m != nil {
		return m.EventId
	}
	return ""
}

func (m *Event) GetEventType() string {
	if m != nil {
		return m.EventType
	}
	return ""
}

func (m *Event) GetEventData() string {
	if m != nil {
		return m.EventData
	}
	return ""
}

func (m *Event) GetAggregateId() string {
	if m != nil {
		return m.AggregateId
	}
	return ""
}

func (m *Event) GetAggregateType() string {
	if m != nil {
		return m.AggregateType
	}
	return ""
}

func (m *Event) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

type EventFilter struct {
	EventId      string `protobuf:"bytes,1,opt,name=event_id,json=eventId" json:"event_id,omitempty"`
	AggregatedId string `protobuf:"bytes,2,opt,name=aggregated_id,json=aggregatedId" json:"aggregated_id,omitempty"`
}

func (m *EventFilter) Reset()                    { *m = EventFilter{} }
func (m *EventFilter) String() string            { return proto.CompactTextString(m) }
func (*EventFilter) ProtoMessage()               {}
func (*EventFilter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *EventFilter) GetEventId() string {
	if m != nil {
		return m.EventId
	}
	return ""
}

func (m *EventFilter) GetAggregatedId() string {
	if m != nil {
		return m.AggregatedId
	}
	return ""
}

type EventResponse struct {
	Events []*Event `protobuf:"bytes,1,rep,name=events" json:"events,omitempty"`
}

func (m *EventResponse) Reset()                    { *m = EventResponse{} }
func (m *EventResponse) String() string            { return proto.CompactTextString(m) }
func (*EventResponse) ProtoMessage()               {}
func (*EventResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *EventResponse) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

type Response struct {
	IsSuccess bool   `protobuf:"varint,1,opt,name=is_success,json=isSuccess" json:"is_success,omitempty"`
	Err       string `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Response) GetIsSuccess() bool {
	if m != nil {
		return m.IsSuccess
	}
	return false
}

func (m *Response) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func init() {
	proto.RegisterType((*Event)(nil), "pb.Event")
	proto.RegisterType((*EventFilter)(nil), "pb.EventFilter")
	proto.RegisterType((*EventResponse)(nil), "pb.EventResponse")
	proto.RegisterType((*Response)(nil), "pb.Response")
}

func init() { proto.RegisterFile("eventstore.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 308 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0x3f, 0x6f, 0xf2, 0x30,
	0x10, 0xc6, 0xdf, 0xc0, 0x0b, 0x24, 0x17, 0x68, 0xa9, 0x27, 0x17, 0x09, 0x09, 0x52, 0x55, 0x62,
	0x42, 0x15, 0x1d, 0x3b, 0xf6, 0x9f, 0x18, 0xba, 0x40, 0x77, 0xe4, 0xc4, 0xa7, 0x10, 0x09, 0x25,
	0x96, 0xed, 0x56, 0xe2, 0xfb, 0xf5, 0x83, 0x55, 0x3e, 0xa7, 0x71, 0xa7, 0x6e, 0xf6, 0x3d, 0x3f,
	0xdf, 0xf3, 0x9c, 0x0f, 0xa6, 0xf8, 0x89, 0xb5, 0x35, 0xb6, 0xd1, 0xb8, 0x56, 0xba, 0xb1, 0x0d,
	0xeb, 0xa9, 0x3c, 0xfb, 0x8a, 0x60, 0xf0, 0xec, 0x04, 0x76, 0x0d, 0x31, 0x11, 0x87, 0x4a, 0xf2,
	0x68, 0x11, 0xad, 0x92, 0xdd, 0x88, 0xee, 0x5b, 0xc9, 0xe6, 0x00, 0x5e, 0xb2, 0x67, 0x85, 0xbc,
	0x47, 0x62, 0x42, 0x95, 0xf7, 0xb3, 0xc2, 0x20, 0x4b, 0x61, 0x05, 0xef, 0xff, 0x92, 0x9f, 0x84,
	0x15, 0x6c, 0x09, 0x63, 0x51, 0x96, 0x1a, 0x4b, 0x61, 0xd1, 0x35, 0xff, 0x4f, 0x40, 0xda, 0xd5,
	0xb6, 0x92, 0xdd, 0xc2, 0x45, 0x40, 0xc8, 0x64, 0x40, 0xd0, 0xa4, 0xab, 0x92, 0x11, 0x87, 0x51,
	0x71, 0x14, 0x75, 0x8d, 0x27, 0x3e, 0xf4, 0x09, 0xdb, 0x6b, 0xf6, 0x06, 0x29, 0x4d, 0xf1, 0x52,
	0x9d, 0x2c, 0xea, 0xbf, 0x66, 0xb9, 0x81, 0xd0, 0x54, 0x3a, 0xdd, 0x8f, 0x13, 0x22, 0xca, 0xad,
	0xcc, 0x36, 0x30, 0xa1, 0x76, 0x3b, 0x34, 0xaa, 0xa9, 0x0d, 0xb2, 0x25, 0x0c, 0xfd, 0xf7, 0xf1,
	0x68, 0xd1, 0x5f, 0xa5, 0x9b, 0x64, 0xad, 0xf2, 0xb5, 0x47, 0x5a, 0x21, 0x7b, 0x80, 0xb8, 0xc3,
	0xe7, 0x00, 0x95, 0x39, 0x98, 0x8f, 0xa2, 0x40, 0x63, 0x28, 0x41, 0xbc, 0x4b, 0x2a, 0xb3, 0xf7,
	0x05, 0x36, 0x85, 0x3e, 0x6a, 0xdd, 0x3a, 0xbb, 0xe3, 0xe6, 0x08, 0x40, 0xdd, 0xf6, 0x6e, 0x3d,
	0x6c, 0x05, 0xe9, 0xa3, 0x46, 0x61, 0xd1, 0x6f, 0x26, 0x98, 0xcd, 0xc6, 0xee, 0xf8, 0x63, 0x93,
	0xfd, 0x63, 0x77, 0x10, 0xbf, 0xa2, 0xf5, 0xd8, 0x65, 0x87, 0xf9, 0x5f, 0x98, 0x5d, 0x85, 0x90,
	0xdd, 0x8b, 0x7c, 0x48, 0xbb, 0xbf, 0xff, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xe5, 0x23, 0x16, 0x38,
	0x0f, 0x02, 0x00, 0x00,
}
