// Code generated by protoc-gen-go. DO NOT EDIT.
// source: payment.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type PaymentCreatedCommand struct {
	PaymentId  string                        `protobuf:"bytes,1,opt,name=payment_id,json=paymentId" json:"payment_id,omitempty"`
	SenderId   string                        `protobuf:"bytes,2,opt,name=sender_id,json=senderId" json:"sender_id,omitempty"`
	ReceiverId string                        `protobuf:"bytes,3,opt,name=receiver_id,json=receiverId" json:"receiver_id,omitempty"`
	Status     string                        `protobuf:"bytes,4,opt,name=status" json:"status,omitempty"`
	Amount     int64                         `protobuf:"varint,5,opt,name=amount" json:"amount,omitempty"`
	ListItems  []*PaymentCreatedCommand_Item `protobuf:"bytes,6,rep,name=list_items,json=listItems" json:"list_items,omitempty"`
}

func (m *PaymentCreatedCommand) Reset()                    { *m = PaymentCreatedCommand{} }
func (m *PaymentCreatedCommand) String() string            { return proto.CompactTextString(m) }
func (*PaymentCreatedCommand) ProtoMessage()               {}
func (*PaymentCreatedCommand) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *PaymentCreatedCommand) GetPaymentId() string {
	if m != nil {
		return m.PaymentId
	}
	return ""
}

func (m *PaymentCreatedCommand) GetSenderId() string {
	if m != nil {
		return m.SenderId
	}
	return ""
}

func (m *PaymentCreatedCommand) GetReceiverId() string {
	if m != nil {
		return m.ReceiverId
	}
	return ""
}

func (m *PaymentCreatedCommand) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *PaymentCreatedCommand) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *PaymentCreatedCommand) GetListItems() []*PaymentCreatedCommand_Item {
	if m != nil {
		return m.ListItems
	}
	return nil
}

type PaymentCreatedCommand_Item struct {
	ItemId    string `protobuf:"bytes,1,opt,name=item_id,json=itemId" json:"item_id,omitempty"`
	ItemName  string `protobuf:"bytes,2,opt,name=item_name,json=itemName" json:"item_name,omitempty"`
	UnitPrice int64  `protobuf:"varint,3,opt,name=unit_price,json=unitPrice" json:"unit_price,omitempty"`
	Quantity  int32  `protobuf:"varint,4,opt,name=quantity" json:"quantity,omitempty"`
}

func (m *PaymentCreatedCommand_Item) Reset()                    { *m = PaymentCreatedCommand_Item{} }
func (m *PaymentCreatedCommand_Item) String() string            { return proto.CompactTextString(m) }
func (*PaymentCreatedCommand_Item) ProtoMessage()               {}
func (*PaymentCreatedCommand_Item) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0, 0} }

func (m *PaymentCreatedCommand_Item) GetItemId() string {
	if m != nil {
		return m.ItemId
	}
	return ""
}

func (m *PaymentCreatedCommand_Item) GetItemName() string {
	if m != nil {
		return m.ItemName
	}
	return ""
}

func (m *PaymentCreatedCommand_Item) GetUnitPrice() int64 {
	if m != nil {
		return m.UnitPrice
	}
	return 0
}

func (m *PaymentCreatedCommand_Item) GetQuantity() int32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

type PaymentFinishedCommand struct {
	PaymentId  string `protobuf:"bytes,1,opt,name=payment_id,json=paymentId" json:"payment_id,omitempty"`
	SenderId   string `protobuf:"bytes,2,opt,name=sender_id,json=senderId" json:"sender_id,omitempty"`
	ReceiverId string `protobuf:"bytes,3,opt,name=receiver_id,json=receiverId" json:"receiver_id,omitempty"`
	Amount     int64  `protobuf:"varint,4,opt,name=amount" json:"amount,omitempty"`
}

func (m *PaymentFinishedCommand) Reset()                    { *m = PaymentFinishedCommand{} }
func (m *PaymentFinishedCommand) String() string            { return proto.CompactTextString(m) }
func (*PaymentFinishedCommand) ProtoMessage()               {}
func (*PaymentFinishedCommand) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *PaymentFinishedCommand) GetPaymentId() string {
	if m != nil {
		return m.PaymentId
	}
	return ""
}

func (m *PaymentFinishedCommand) GetSenderId() string {
	if m != nil {
		return m.SenderId
	}
	return ""
}

func (m *PaymentFinishedCommand) GetReceiverId() string {
	if m != nil {
		return m.ReceiverId
	}
	return ""
}

func (m *PaymentFinishedCommand) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func init() {
	proto.RegisterType((*PaymentCreatedCommand)(nil), "pb.PaymentCreatedCommand")
	proto.RegisterType((*PaymentCreatedCommand_Item)(nil), "pb.PaymentCreatedCommand.Item")
	proto.RegisterType((*PaymentFinishedCommand)(nil), "pb.PaymentFinishedCommand")
}

func init() { proto.RegisterFile("payment.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 283 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x91, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x95, 0xa6, 0x0d, 0xcd, 0x55, 0x2c, 0x96, 0x28, 0x51, 0x11, 0x10, 0x75, 0xca, 0x94,
	0x01, 0x66, 0xa6, 0x4a, 0x48, 0x59, 0x50, 0x95, 0x17, 0x88, 0x9c, 0xfa, 0x24, 0x2c, 0x61, 0x27,
	0xc4, 0x17, 0x50, 0x1f, 0x82, 0x37, 0xe4, 0x61, 0xd0, 0x39, 0x2e, 0x30, 0x30, 0xb3, 0xdd, 0xff,
	0xfd, 0xb6, 0x75, 0xff, 0x6f, 0x38, 0xef, 0xe5, 0xd1, 0xa0, 0xa5, 0xb2, 0x1f, 0x3a, 0xea, 0xc4,
	0xac, 0x6f, 0xb7, 0x9f, 0x33, 0xb8, 0xd8, 0x4f, 0x74, 0x37, 0xa0, 0x24, 0x54, 0xbb, 0xce, 0x18,
	0x69, 0x95, 0xb8, 0x06, 0x08, 0xc7, 0x1b, 0xad, 0xb2, 0x28, 0x8f, 0x8a, 0xb4, 0x4e, 0x03, 0xa9,
	0x94, 0xb8, 0x82, 0xd4, 0xa1, 0x55, 0x38, 0xb0, 0x3b, 0xf3, 0xee, 0x72, 0x02, 0x95, 0x12, 0xb7,
	0xb0, 0x1a, 0xf0, 0x80, 0xfa, 0x6d, 0xb2, 0x63, 0x6f, 0xc3, 0x09, 0x55, 0x4a, 0xac, 0x21, 0x71,
	0x24, 0x69, 0x74, 0xd9, 0xdc, 0x7b, 0x41, 0x31, 0x97, 0xa6, 0x1b, 0x2d, 0x65, 0x8b, 0x3c, 0x2a,
	0xe2, 0x3a, 0x28, 0xf1, 0x00, 0xf0, 0xa2, 0x1d, 0x35, 0x9a, 0xd0, 0xb8, 0x2c, 0xc9, 0xe3, 0x62,
	0x75, 0x77, 0x53, 0xf6, 0x6d, 0xf9, 0xe7, 0xee, 0x65, 0x45, 0x68, 0xea, 0x94, 0x6f, 0xf0, 0xe4,
	0x36, 0xef, 0x30, 0xe7, 0x41, 0x5c, 0xc2, 0x19, 0xbf, 0xf0, 0x13, 0x28, 0x61, 0x39, 0xa5, 0xf1,
	0x86, 0x95, 0x06, 0x4f, 0x69, 0x18, 0x3c, 0x49, 0x83, 0xdc, 0xc4, 0x68, 0x35, 0x35, 0xfd, 0xa0,
	0x0f, 0xe8, 0xc3, 0xc4, 0x75, 0xca, 0x64, 0xcf, 0x40, 0x6c, 0x60, 0xf9, 0x3a, 0x4a, 0x4b, 0x9a,
	0x8e, 0x3e, 0xcd, 0xa2, 0xfe, 0xd6, 0xdb, 0x8f, 0x08, 0xd6, 0x61, 0xc5, 0x47, 0x6d, 0xb5, 0x7b,
	0xfe, 0xbf, 0x7e, 0x43, 0x8f, 0xf3, 0xdf, 0x3d, 0xb6, 0x89, 0xff, 0xf9, 0xfb, 0xaf, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x76, 0xf2, 0xb3, 0xfe, 0x0a, 0x02, 0x00, 0x00,
}
